#line 2 "CodeSmartCppLex.c"
/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 117
#define YY_END_OF_BUFFER 118
static yyconst short int yy_accept[351] =
    {   0,
      116,  116,  118,  117,    1,    3,    2,   81,  117,   69,
       83,   76,  117,   66,   67,   77,   78,   68,   79,   75,
       82,   61,   60,   89,   90,   84,   91,   85,   88,   73,
       74,   86,   59,   59,   59,   59,   59,   59,   59,   59,
       59,   59,   59,   59,   59,   59,   59,   59,   59,   59,
       59,   71,   87,   72,   80,    1,    3,    0,    2,  103,
        0,   65,    0,   70,  108,  104,  113,    0,    0,  106,
       96,  109,   97,  110,   94,   92,   63,  107,   63,   61,
        0,    0,   61,   61,    0,   60,   60,   60,   93,   98,
      100,  102,  101,   99,  114,   59,   59,   59,   59,   59,

       59,   59,   59,   13,   59,   59,   59,   59,   59,   59,
       59,   59,   24,   59,    0,    0,   59,   59,   59,   59,
       59,   59,   59,   59,   59,   59,   59,   59,   59,   59,
       59,   59,   59,   59,  115,  105,    0,    0,   64,    0,
        0,   95,    0,   63,    0,   63,   61,   62,   60,  111,
      112,   59,   59,   59,   59,   59,   59,   59,   59,   59,
       59,   59,   59,   59,   59,   59,   59,   22,   59,   59,
       59,   59,   59,   59,   28,   59,   59,   51,   59,   59,
       59,   59,   59,   59,   59,   59,   59,   59,   59,   59,
       59,   59,   59,   59,   59,   59,   59,   59,   59,   59,

       59,    0,    0,    0,    0,    0,   63,   62,   62,    4,
       59,    6,    7,   59,   59,   59,   59,   59,   59,   59,
       15,   16,   59,   18,   59,   59,   59,   59,   23,   59,
       59,   59,   59,   29,   30,   59,   59,   59,   59,   59,
       59,   59,   59,   59,   59,   59,   59,   59,   59,   57,
       59,   59,   59,   59,   59,   44,   59,   59,    0,    0,
        0,    0,   62,    5,   47,    8,   59,   59,   59,   59,
       59,   17,   19,   59,   21,   59,   25,   59,   59,   59,
       59,   59,   59,   59,   59,   59,   59,   59,   34,   59,
       59,   59,   59,   59,   59,   41,   42,   59,   59,   59,

       46,   59,   59,   11,   48,   14,   20,   49,   26,   59,
       50,   59,   59,   31,   59,   59,   56,   59,   33,   35,
       36,   37,   38,   39,   59,   59,   59,   59,   59,   10,
       12,   27,   59,   59,   55,   59,   59,   40,   59,   58,
       59,    9,   52,   53,   59,   32,   43,   45,   54,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        4,    5,    6,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    7,    8,    9,   10,    1,   11,   12,   13,   14,
       15,   16,   17,   18,   19,   20,   21,   22,   23,   23,
       23,   23,   23,   23,   23,   24,   24,   25,   26,   27,
       28,   29,   30,    1,   36,   37,   38,   39,   40,   41,
       42,   43,   44,   35,   45,   46,   47,   48,   49,   50,
       35,   51,   52,   53,   54,   55,   56,   57,   58,   59,
       31,   32,   33,   34,   35,    1,   36,   37,   38,   39,

       40,   41,   42,   43,   44,   35,   45,   46,   47,   48,
       49,   50,   35,   51,   52,   53,   54,   55,   56,   57,
       58,   59,   60,   61,   62,   63,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[64] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    3,    1,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    5,    6,    1,    1,    1,    1,    1,    3,
        1,    3,    1,    1,    7,    5,    5,    6,    6,    6,
        5,    7,    7,    7,    7,    6,    7,    8,    7,    7,
        8,    7,    8,    6,    8,    7,    8,    7,    7,    1,
        1,    1,    1
    } ;

static yyconst short int yy_base[357] =
    {   0,
        0,    0,  559,  560,   62,  560,   68,  530,   67,  547,
      528,   65,  523,  560,  560,  526,   61,  560,   62,   63,
      525,   60,   72,  527,  560,   70,  523,   73,  560,  560,
      560,  522,    0,  495,  497,   67,   71,   73,   58,  498,
       67,  114,  506,   78,   71,  505,   88,   91,  496,   91,
      500,  560,   77,  560,  560,  148,  560,  162,  168,  560,
      127,  560,  120,  560,  560,  560,  560,  116,  123,  560,
      560,  560,  560,  560,  526,  560,  138,  560,  159,  166,
      171,  179,  487,  494,  185,  193,  485,  492,  560,  509,
      560,  560,  560,  508,  560,    0,  482,  494,  481,  496,

      495,  482,  146,  475,   95,  165,  477,  474,  477,  474,
      480,  470,  137,  189,  205,  490,  473,  472,  463,  478,
      477,  192,  479,  176,  466,  189,  194,  470,  469,  462,
      199,  460,  188,  466,  560,  560,  231,  233,  560,  236,
      242,  560,  267,  560,  238,  253,  560,  198,  560,  560,
      560,  460,  472,  467,  455,  453,  104,  249,  464,  466,
      461,  461,  456,  452,  449,  457,  460,    0,  455,  445,
      453,  453,  445,  446,    0,  449,  446,    0,  436,  435,
      443,  429,  430,  436,  437,  426,  428,  430,  437,  423,
      421,  421,  421,  432,  431,  421,  425,  412,  425,  423,

      412,  278,  302,  275,  331,  280,  290,  392,  398,    0,
      391,    0,    0,  376,  374,  382,  370,  375,  369,  375,
        0,    0,  379,    0,  368,  367,  361,  365,    0,  371,
      371,  356,  361,    0,    0,  372,  361,  352,  362,  357,
      351,  342,  342,  339,  351,  341,  345,  347,  346,    0,
      344,  341,  333,  338,  325,    0,  325,  337,  283,  364,
      295,  393,  560,    0,    0,    0,  328,  329,  334,  326,
      325,    0,    0,  316,    0,  323,    0,  320,  321,  319,
      305,  308,  320,  299,  313,  312,  296,  300,    0,  308,
      305,  307,  284,  292,  293,    0,    0,  284,  294,  285,

        0,  274,  270,  283,    0,    0,    0,    0,    0,  281,
        0,  271,  283,    0,  278,  264,    0,  276,    0,    0,
        0,    0,    0,    0,  268,  266,  259,  250,  255,    0,
        0,    0,  216,  211,    0,  206,  159,    0,  158,    0,
       97,    0,    0,    0,   49,    0,    0,    0,    0,  560,
      434,  442,  446,  452,  458,  462
    } ;

static yyconst short int yy_def[357] =
    {   0,
      350,    1,  350,  350,  350,  350,  350,  350,  351,  350,
      350,  350,  352,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      351,  350,  354,  350,  350,  350,  350,  352,  355,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  353,  353,  353,  353,  353,

      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  351,  352,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  350,  350,  351,  350,  350,  352,
      350,  350,  350,  350,  350,  350,  350,  356,  350,  350,
      350,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,

      353,  351,  351,  352,  352,  350,  350,  350,  350,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  351,  351,
      352,  352,  350,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,

      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,    0,
      350,  350,  350,  350,  350,  350
    } ;

static yyconst short int yy_nxt[624] =
    {   0,
        4,    5,    6,    7,    7,    7,    5,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   20,
       21,   22,   23,   23,   24,   25,   26,   27,   28,   29,
       30,    4,   31,   32,   33,   34,   35,   36,   37,   38,
       39,   40,   33,   41,   33,   42,   33,   43,   44,   45,
       46,   47,   48,   49,   50,   51,   33,   33,   33,   52,
       53,   54,   55,   56,   57,   58,   58,   58,   56,   58,
       57,   59,   59,   59,   58,   62,   66,   71,   76,   79,
       73,   80,   80,   81,   77,   77,   77,  349,   72,   74,
       75,   79,   67,   86,   86,   86,   90,   91,   63,   82,

       93,   94,   99,  109,  135,   83,  110,  113,  111,  100,
      103,   82,  101,   84,  114,  102,   85,   87,  105,  104,
      106,  122,  115,  107,  123,   88,  116,  120,  139,  108,
      125,  126,  121,  129,  132,   62,  348,  136,  161,  133,
      127,  137,  137,  128,  140,  140,  162,   69,  130,   56,
       57,   58,   58,   58,   56,  215,  216,  117,   63,   77,
       77,   77,  118,   58,   57,   58,   58,   58,   58,   58,
       57,   59,   59,   59,   58,  171,  138,  143,  144,  141,
       77,   77,   77,  144,  172,   79,  158,   80,   80,   81,
       79,  159,   81,   81,   81,  145,  347,  145,  143,  144,

      146,  146,  146,  163,  144,   82,  148,  148,  148,  346,
       82,   83,   79,   62,   86,   86,   86,  185,  164,   84,
      148,  148,  148,  148,  148,  148,  173,  181,  186,  190,
      188,  199,   82,  200,  174,  182,   63,  195,   87,   62,
      183,  175,  196,  208,  191,  345,   88,  189,  139,  344,
      197,  209,  202,  202,  203,  203,  203,  204,  204,  146,
      146,  146,   63,  205,  205,  205,  343,   69,  203,  203,
      203,  203,  203,  203,  146,  146,  146,  205,  205,  205,
      205,  205,  205,  206,  217,  206,   62,  139,  207,  207,
      207,   62,  218,  144,  342,  341,  261,  261,  144,  259,

      259,  207,  207,  207,  340,  339,   69,  139,  338,   63,
       62,  207,  207,  207,   63,  337,  336,  335,  334,  333,
      332,  331,  330,  260,  260,  260,   69,  329,  328,  327,
      144,  326,  325,   63,  324,  144,  323,  260,  260,  260,
      260,  260,  260,  139,  322,  321,  320,  319,  318,  317,
      316,  315,  262,  262,  262,  314,  313,  312,  311,  310,
      309,  308,   69,  307,  306,  305,  262,  262,  262,  262,
      262,  262,   62,  304,  303,  302,  301,  300,  299,  298,
      297,  296,  295,  294,  293,  260,  260,  260,  292,  291,
      290,  289,  288,  287,  286,   63,  285,  284,  283,  260,

      260,  260,  260,  260,  260,  139,  282,  281,  280,  279,
      278,  277,  276,  275,  262,  262,  262,  274,  273,  272,
      271,  270,  269,  268,   69,  267,  266,  265,  262,  262,
      262,  262,  262,  262,   61,  264,   61,   61,   61,   61,
       61,   61,   68,  263,   68,  263,   68,   68,   68,   68,
       96,   96,   96,   96,   61,   61,   61,  258,  257,   61,
       68,   68,   68,  256,  255,   68,  148,  148,  254,  253,
      252,  251,  250,  249,  248,  247,  246,  245,  244,  243,
      242,  241,  240,  239,  238,  237,  236,  235,  234,  233,
      232,  231,  230,  229,  228,  227,  226,  225,  224,  223,

      222,  221,  220,  219,  214,  213,  212,  211,  210,  201,
      198,  194,  193,  192,  187,  184,  180,  179,  178,  177,
      176,   69,  170,  169,  168,  167,  166,  165,  160,  157,
      156,  155,  154,  153,  152,  151,  150,  149,  149,  147,
      147,  142,  134,  131,  124,  119,  112,   98,   97,   95,
       92,   89,   78,   70,   69,   65,   64,   60,  350,    3,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,

      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350
    } ;

static yyconst short int yy_chk[624] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    5,    5,    5,    5,    5,    5,    7,
        7,    7,    7,    7,    7,    9,   12,   17,   20,   22,
       19,   22,   22,   22,   20,   20,   20,  345,   17,   19,
       19,   23,   12,   23,   23,   23,   26,   26,    9,   22,

       28,   28,   36,   39,   53,   22,   39,   41,   39,   36,
       37,   23,   36,   22,   41,   36,   22,   23,   38,   37,
       38,   45,   42,   38,   45,   23,   42,   44,   68,   38,
       47,   47,   44,   48,   50,   61,  341,   53,  105,   50,
       47,   63,   63,   47,   69,   69,  105,   68,   48,   56,
       56,   56,   56,   56,   56,  157,  157,   42,   61,   77,
       77,   77,   42,   58,   58,   58,   58,   58,   58,   59,
       59,   59,   59,   59,   59,  113,   63,   77,   77,   69,
       79,   79,   79,   77,  113,   80,  103,   80,   80,   80,
       81,  103,   81,   81,   81,   82,  339,   82,   79,   79,

       82,   82,   82,  106,   79,   80,   85,   85,   85,  337,
       81,   80,   86,  115,   86,   86,   86,  124,  106,   80,
       85,   85,   85,   85,   85,   85,  114,  122,  124,  127,
      126,  133,   86,  133,  114,  122,  115,  131,   86,  137,
      122,  114,  131,  148,  127,  336,   86,  126,  140,  334,
      131,  148,  137,  137,  138,  138,  138,  140,  140,  145,
      145,  145,  137,  141,  141,  141,  333,  140,  138,  138,
      138,  138,  138,  138,  146,  146,  146,  141,  141,  141,
      141,  141,  141,  143,  158,  143,  202,  204,  143,  143,
      143,  259,  158,  146,  329,  328,  204,  204,  146,  202,

      202,  206,  206,  206,  327,  326,  204,  261,  325,  202,
      203,  207,  207,  207,  259,  318,  316,  315,  313,  312,
      310,  304,  303,  203,  203,  203,  261,  302,  300,  299,
      207,  298,  295,  203,  294,  207,  293,  203,  203,  203,
      203,  203,  203,  205,  292,  291,  290,  288,  287,  286,
      285,  284,  205,  205,  205,  283,  282,  281,  280,  279,
      278,  276,  205,  274,  271,  270,  205,  205,  205,  205,
      205,  205,  260,  269,  268,  267,  258,  257,  255,  254,
      253,  252,  251,  249,  248,  260,  260,  260,  247,  246,
      245,  244,  243,  242,  241,  260,  240,  239,  238,  260,

      260,  260,  260,  260,  260,  262,  237,  236,  233,  232,
      231,  230,  228,  227,  262,  262,  262,  226,  225,  223,
      220,  219,  218,  217,  262,  216,  215,  214,  262,  262,
      262,  262,  262,  262,  351,  211,  351,  351,  351,  351,
      351,  351,  352,  209,  352,  208,  352,  352,  352,  352,
      353,  353,  353,  353,  354,  354,  354,  201,  200,  354,
      355,  355,  355,  199,  198,  355,  356,  356,  197,  196,
      195,  194,  193,  192,  191,  190,  189,  188,  187,  186,
      185,  184,  183,  182,  181,  180,  179,  177,  176,  174,
      173,  172,  171,  170,  169,  167,  166,  165,  164,  163,

      162,  161,  160,  159,  156,  155,  154,  153,  152,  134,
      132,  130,  129,  128,  125,  123,  121,  120,  119,  118,
      117,  116,  112,  111,  110,  109,  108,  107,  104,  102,
      101,  100,   99,   98,   97,   94,   90,   88,   87,   84,
       83,   75,   51,   49,   46,   43,   40,   35,   34,   32,
       27,   24,   21,   16,   13,   11,   10,    8,    3,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,

      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "CodeSmartCpp.l"
#define INITIAL 0
#line 2 "CodeSmartCpp.l"

    /* Copyright (C) 1989-1991 James A. Roskind, All rights reserved.
    This lexer description was written by James A.  Roskind.  Copying
    of  this  file, as a whole, is permitted providing this notice is
    intact  and  applicable   in   all   complete   copies.    Direct
    translations  as a whole to other lexer generator input languages
    (or lexical description languages)  is  permitted  provided  that
    this  notice  is  intact and applicable in all such copies, along
    with a disclaimer that  the  contents  are  a  translation.   The
    reproduction  of derived files or text, such as modified versions
    of this file, or the output of scanner generators, is  permitted,
    provided   the  resulting  work  includes  the  copyright  notice
    "Portions Copyright (c) 1989, 1990 James  A.   Roskind".  Derived
    products  must  also  provide  the notice "Portions Copyright (c)
    1989, 1990 James A.  Roskind" in  a  manner  appropriate  to  the
    utility,   and  in  keeping  with  copyright  law  (e.g.:  EITHER
    displayed when first invoked/executed; OR displayed  continuously
    on  display terminal; OR via placement in the object code in form
    readable in a printout, with or near the title of the work, or at
    the end of the file).  No royalties, licenses or  commissions  of
    any  kind  are  required  to copy this file, its translations, or
    derivative products, when the copies are made in compliance  with
    this  notice.  Persons  or  corporations  that  do make copies in
    compliance  with  this  notice  may  charge  whatever  price   is
    agreeable  to  a buyer, for such copies or derivative works. THIS
    FILE IS PROVIDED ``AS IS'' AND WITHOUT  ANY  EXPRESS  OR  IMPLIED
    WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED WARRANTIES
    OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.

    James A. Roskind
    Independent Consultant
    516 Latania Palm Drive
    Indialantic FL, 32903
    (407)729-4348
    jar@hq.ileaf.com
    or !uunet!leafusa!jar

    ---end of copyright notice---


COMMENTS-

My  goal  is  to  see  software  developers adopt my C++ grammar as a
standard until such time as a better  standard  is  accessible.   The
only  way  to  get it to become a standard, is to be sure that people
know that derivations are based on a specific work.   The  intent  of
releasing  this Flex input file is to facilitate experimentation with
my C++ grammar. The intent  of  the  copyright  notice  is  to  allow
arbitrary  commercial and non-commercial use of this file, as long as
reference is given to my standardization effort.   Without  reference
to  a specific standard, many alternative grammars would develop.  By
referring to the standard, the C++ grammar is given publicity,  which
should  lead  to further use in compatible products and systems.  The
benefits  of  such  a  standard  to  commercial  products  (browsers,
beautifiers,  translators,  compilers,  ) should be obvious to the
developers, in that other compatible products will  emerge,  and  the
value  of  all  conforming  products  will rise.  Most developers are
aware of the value of acquiring  a  fairly  complete  grammar  for  a
language,  and  the  copyright  notice (and the resulting affiliation
with my work) should not be too high a price to pay.  By copyrighting
my work, I have some minor control over what this standard is, and  I
can  (hopefully)  keep it from degrading without my approval.  I will
consistently attempt to provide upgraded grammars that are  compliant
with  the  current  art, and the ANSI C++ Committee recommendation in
particular.  A  developer  is  never  prevented  from  modifying  the
grammar or this file to improve it in whatever way is seen fit. There
is  also  no  restriction on the sale of copies, or derivative works,
providing the request in the copyright notice are satisfied.

If you are not "copying" my work, but  are  rather  only  abstracting
some of my work, an acknowledgment with references to such a standard
would  be  appreciated.  Specifically, agreements with my grammar and
its resolution of otherwise ambiguous constructs, should be noted.

Simply put: "make whatever use you would like of the grammar and this
file, but include the ``portions Copyright '' as  a  reference  to
this standard."


*/

/* Last modified 7/4/91, Version 2.0 */

/* File cpp5.l, becomes lex.yy.c after processing by FLEX  */

/* This file is a dramatically cut down version of the FLEX input file
used in  my  ANSI  C  Preprocessor.   The  executable  version  of  my
preprocessor  is  available on many platforms (shareware), but this is
the only source extract that is currently being distributed.   If  you
need   a   full   ANSI   C  preprocessor,  with  extensive  diagnostic
capabilities and customization facilities, please contact  me  at  the
addresses given above.  Current platforms include IBMPC (DOS/OS2), Sun
(SPARC   and  Motorola),  and  IBM  R/6000.     end  of  commercial
announcement.

This file is being distributed to facilitate experimentation  and  use
of my C and C++ grammar.


Comment  removal  must  be done during the lexing, as context (such as
enclosure in string literals) must be  observed.   For  this  cut-down
lexer,  we  will  assume that comments have been removed (don't assume
this if you are writing a compiler or browser!).


/* For each IDENTIFIER like string that is found,  there  are  several
distinct interpretations that can be applied:

1)  The  preprocessor  may  interpret  the  string as a "keyword" in a
directive (eg: "pragma" or "include", "defined").

2) The parser may interpret the string as a keyword. (eg: "int").

3) Both parser and preprocessor may interpret the string as a  keyword
(eg: "if").

Since  this  file  is based on source that actually lexically analyses
text for both preprocessing and parsing, macro definitions  were  used
throughout.   The macro definitions supplied here have been customized
to a C++ parse only, and  all  preprocessor  keywords  are  passed  as
IDENTIFIER  or  TYPEDEFname.   Also, since there is no symbol table to
interrogate to decide whether a string  is  a  TYPEDEFname,  I  simply
assume  that  any  identifier beginning with an upper case letter is a
TYPEDEFname.  This hack  should  allow  you  to  check  out  how  code
segments  are  parsed  using my grammar.  Unfortunately, if you really
want to parse major league code, you have to write a symbol table, and
maintain appropriate scoping information.



*/


/* Included code before lex code */
/*************** Includes and Defines *****************************/


#include "CodeSmartCppYacc.h" /* YACC generated definitions based on C++ grammar */

/* typedef char * YYSTYPE; interface with lexer: should be  in  header
                        file*/

char  *  yylval;  /*  We  will always point at the text of the lexeme.
          This makes it easy to print out nice trees when  YYDEBUG  is
          enabled.   (see  C++  grammar  file  and  its  definition of
          YYDEBUG_LEXER_TEXT to be "yylval" */



#define WHITE_RETURN(x) /* do nothing */

#define NEW_LINE_RETURN() WHITE_RETURN('\n')

#define PA_KEYWORD_RETURN(x)   RETURN_VAL(x)  /* standard C PArser Keyword */
#define CPP_KEYWORD_RETURN(x)  PA_KEYWORD_RETURN(x)  /* C++ keyword */
#define PPPA_KEYWORD_RETURN(x) RETURN_VAL(x)  /* both PreProcessor and PArser
keyword */
#define PP_KEYWORD_RETURN(x)   IDENTIFIER_RETURN()

#define IDENTIFIER_RETURN() RETURN_VAL(isaTYPE(yytext)?TYPEDEFname:IDENTIFIER)

#define PPOP_RETURN(x)       RETURN_VAL((int)*yytext) /* PreProcess and
Parser operator */
#define NAMED_PPOP_RETURN(x) /* error: PreProcessor ONLY operator;  Do nothing */
#define ASCIIOP_RETURN(x)    RETURN_VAL((int)*yytext) /* a single character
operator */
#define NAMEDOP_RETURN(x)    RETURN_VAL(x)            /* a multichar
operator, with a name */

#define NUMERICAL_RETURN(x) RETURN_VAL(x)            /* some sort of constant */
#define LITERAL_RETURN(x)   RETURN_VAL(x)            /* a string literal */

#define RETURN_VAL(x) yylval = yytext; return(x);


#line 795 "CodeSmartCppLex.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 208 "CodeSmartCpp.l"



#line 950 "CodeSmartCppLex.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 351 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 560 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 211 "CodeSmartCpp.l"
{
            WHITE_RETURN(' ');
            }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 215 "CodeSmartCpp.l"
{
            WHITE_RETURN(' ');
            }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 220 "CodeSmartCpp.l"
{
            NEW_LINE_RETURN();
            }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 224 "CodeSmartCpp.l"
{PA_KEYWORD_RETURN(AUTO);}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 225 "CodeSmartCpp.l"
{PA_KEYWORD_RETURN(BREAK);}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 226 "CodeSmartCpp.l"
{PA_KEYWORD_RETURN(CASE);}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 227 "CodeSmartCpp.l"
{PA_KEYWORD_RETURN(CHAR);}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 228 "CodeSmartCpp.l"
{PA_KEYWORD_RETURN(CONST);}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 229 "CodeSmartCpp.l"
{PA_KEYWORD_RETURN(CONTINUE);}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 230 "CodeSmartCpp.l"
{PA_KEYWORD_RETURN(DEFAULT);}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 231 "CodeSmartCpp.l"
{PP_KEYWORD_RETURN(DEFINE);}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 232 "CodeSmartCpp.l"
{PP_KEYWORD_RETURN(OPDEFINED);}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 233 "CodeSmartCpp.l"
{PA_KEYWORD_RETURN(DO);}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 234 "CodeSmartCpp.l"
{PA_KEYWORD_RETURN(DOUBLE);}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 235 "CodeSmartCpp.l"
{PP_KEYWORD_RETURN(ELIF);}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 236 "CodeSmartCpp.l"
{PPPA_KEYWORD_RETURN(ELSE);}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 237 "CodeSmartCpp.l"
{PP_KEYWORD_RETURN(ENDIF);}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 238 "CodeSmartCpp.l"
{PA_KEYWORD_RETURN(ENUM);}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 239 "CodeSmartCpp.l"
{PP_KEYWORD_RETURN(ERROR);}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 240 "CodeSmartCpp.l"
{PA_KEYWORD_RETURN(EXTERN);}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 241 "CodeSmartCpp.l"
{PA_KEYWORD_RETURN(FLOAT);}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 242 "CodeSmartCpp.l"
{PA_KEYWORD_RETURN(FOR);}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 243 "CodeSmartCpp.l"
{PA_KEYWORD_RETURN(GOTO);}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 244 "CodeSmartCpp.l"
{PPPA_KEYWORD_RETURN(IF);}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 245 "CodeSmartCpp.l"
{PP_KEYWORD_RETURN(IFDEF);}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 246 "CodeSmartCpp.l"
{PP_KEYWORD_RETURN(IFNDEF);}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 247 "CodeSmartCpp.l"
{PP_KEYWORD_RETURN(INCLUDE); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 248 "CodeSmartCpp.l"
{PA_KEYWORD_RETURN(INT);}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 249 "CodeSmartCpp.l"
{PP_KEYWORD_RETURN(LINE);}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 250 "CodeSmartCpp.l"
{PA_KEYWORD_RETURN(LONG);}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 251 "CodeSmartCpp.l"
{PP_KEYWORD_RETURN(PRAGMA);}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 252 "CodeSmartCpp.l"
{PA_KEYWORD_RETURN(REGISTER);}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 253 "CodeSmartCpp.l"
{PA_KEYWORD_RETURN(RETURN);}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 254 "CodeSmartCpp.l"
{PA_KEYWORD_RETURN(SHORT);}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 255 "CodeSmartCpp.l"
{PA_KEYWORD_RETURN(SIGNED);}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 256 "CodeSmartCpp.l"
{PA_KEYWORD_RETURN(SIZEOF);}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 257 "CodeSmartCpp.l"
{PA_KEYWORD_RETURN(STATIC);}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 258 "CodeSmartCpp.l"
{PA_KEYWORD_RETURN(STRUCT);}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 259 "CodeSmartCpp.l"
{PA_KEYWORD_RETURN(SWITCH);}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 260 "CodeSmartCpp.l"
{PA_KEYWORD_RETURN(TYPEDEF);}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 261 "CodeSmartCpp.l"
{PP_KEYWORD_RETURN(UNDEF);}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 262 "CodeSmartCpp.l"
{PA_KEYWORD_RETURN(UNION);}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 263 "CodeSmartCpp.l"
{PA_KEYWORD_RETURN(UNSIGNED);}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 264 "CodeSmartCpp.l"
{PA_KEYWORD_RETURN(VOID);}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 265 "CodeSmartCpp.l"
{PA_KEYWORD_RETURN(VOLATILE);}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 266 "CodeSmartCpp.l"
{PA_KEYWORD_RETURN(WHILE);}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 269 "CodeSmartCpp.l"
{CPP_KEYWORD_RETURN(CLASS);}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 270 "CodeSmartCpp.l"
{CPP_KEYWORD_RETURN(DELETE);}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 271 "CodeSmartCpp.l"
{CPP_KEYWORD_RETURN(FRIEND);}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 272 "CodeSmartCpp.l"
{CPP_KEYWORD_RETURN(INLINE);}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 273 "CodeSmartCpp.l"
{CPP_KEYWORD_RETURN(NEW);}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 274 "CodeSmartCpp.l"
{CPP_KEYWORD_RETURN(OPERATOR);}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 275 "CodeSmartCpp.l"
{CPP_KEYWORD_RETURN(OVERLOAD);}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 276 "CodeSmartCpp.l"
{CPP_KEYWORD_RETURN(PROTECTED);}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 277 "CodeSmartCpp.l"
{CPP_KEYWORD_RETURN(PRIVATE);}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 278 "CodeSmartCpp.l"
{CPP_KEYWORD_RETURN(PUBLIC);}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 279 "CodeSmartCpp.l"
{CPP_KEYWORD_RETURN(THIS);}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 280 "CodeSmartCpp.l"
{CPP_KEYWORD_RETURN(VIRTUAL);}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 282 "CodeSmartCpp.l"
{IDENTIFIER_RETURN();}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 284 "CodeSmartCpp.l"
{NUMERICAL_RETURN(INTEGERconstant);}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 285 "CodeSmartCpp.l"
{NUMERICAL_RETURN(OCTALconstant);}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 286 "CodeSmartCpp.l"
{NUMERICAL_RETURN(HEXconstant);}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 287 "CodeSmartCpp.l"
{NUMERICAL_RETURN(FLOATINGconstant);}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 290 "CodeSmartCpp.l"
{
            NUMERICAL_RETURN(CHARACTERconstant);
            }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 295 "CodeSmartCpp.l"
{
            LITERAL_RETURN(STRINGliteral);}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 301 "CodeSmartCpp.l"
{PPOP_RETURN(LP);}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 302 "CodeSmartCpp.l"
{PPOP_RETURN(RP);}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 303 "CodeSmartCpp.l"
{PPOP_RETURN(COMMA);}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 304 "CodeSmartCpp.l"
{NAMED_PPOP_RETURN('#') ;}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 305 "CodeSmartCpp.l"
{NAMED_PPOP_RETURN(POUNDPOUND);}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 307 "CodeSmartCpp.l"
{ASCIIOP_RETURN(LC);}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 308 "CodeSmartCpp.l"
{ASCIIOP_RETURN(RC);}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 309 "CodeSmartCpp.l"
{ASCIIOP_RETURN(LB);}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 310 "CodeSmartCpp.l"
{ASCIIOP_RETURN(RB);}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 311 "CodeSmartCpp.l"
{ASCIIOP_RETURN(DOT);}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 312 "CodeSmartCpp.l"
{ASCIIOP_RETURN(AND);}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 313 "CodeSmartCpp.l"
{ASCIIOP_RETURN(STAR);}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 314 "CodeSmartCpp.l"
{ASCIIOP_RETURN(PLUS);}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 315 "CodeSmartCpp.l"
{ASCIIOP_RETURN(MINUS);}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 316 "CodeSmartCpp.l"
{ASCIIOP_RETURN(NEGATE);}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 317 "CodeSmartCpp.l"
{ASCIIOP_RETURN(NOT);}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 318 "CodeSmartCpp.l"
{ASCIIOP_RETURN(DIV);}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 319 "CodeSmartCpp.l"
{ASCIIOP_RETURN(MOD);}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 320 "CodeSmartCpp.l"
{ASCIIOP_RETURN(LT);}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 321 "CodeSmartCpp.l"
{ASCIIOP_RETURN(GT);}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 322 "CodeSmartCpp.l"
{ASCIIOP_RETURN(XOR);}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 323 "CodeSmartCpp.l"
{ASCIIOP_RETURN(PIPE);}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 324 "CodeSmartCpp.l"
{ASCIIOP_RETURN(QUESTION);}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 325 "CodeSmartCpp.l"
{ASCIIOP_RETURN(COLON);}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 326 "CodeSmartCpp.l"
{ASCIIOP_RETURN(SEMICOLON);}
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 327 "CodeSmartCpp.l"
{ASCIIOP_RETURN(ASSIGN);}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 329 "CodeSmartCpp.l"
{NAMEDOP_RETURN(DOTstar);}
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 330 "CodeSmartCpp.l"
{NAMEDOP_RETURN(CLCL);}
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 331 "CodeSmartCpp.l"
{NAMEDOP_RETURN(ARROW);}
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 332 "CodeSmartCpp.l"
{NAMEDOP_RETURN(ARROWstar);}
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 333 "CodeSmartCpp.l"
{NAMEDOP_RETURN(ICR);}
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 334 "CodeSmartCpp.l"
{NAMEDOP_RETURN(DECR);}
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 335 "CodeSmartCpp.l"
{NAMEDOP_RETURN(LS);}
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 336 "CodeSmartCpp.l"
{NAMEDOP_RETURN(RS);}
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 337 "CodeSmartCpp.l"
{NAMEDOP_RETURN(LE);}
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 338 "CodeSmartCpp.l"
{NAMEDOP_RETURN(GE);}
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 339 "CodeSmartCpp.l"
{NAMEDOP_RETURN(EQ);}
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 340 "CodeSmartCpp.l"
{NAMEDOP_RETURN(NE);}
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 341 "CodeSmartCpp.l"
{NAMEDOP_RETURN(ANDAND);}
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 342 "CodeSmartCpp.l"
{NAMEDOP_RETURN(OROR);}
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 343 "CodeSmartCpp.l"
{NAMEDOP_RETURN(MULTassign);}
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 344 "CodeSmartCpp.l"
{NAMEDOP_RETURN(DIVassign);}
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 345 "CodeSmartCpp.l"
{NAMEDOP_RETURN(MODassign);}
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 346 "CodeSmartCpp.l"
{NAMEDOP_RETURN(PLUSassign);}
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 347 "CodeSmartCpp.l"
{NAMEDOP_RETURN(MINUSassign);}
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 348 "CodeSmartCpp.l"
{NAMEDOP_RETURN(LSassign);}
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 349 "CodeSmartCpp.l"
{NAMEDOP_RETURN(RSassign);}
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 350 "CodeSmartCpp.l"
{NAMEDOP_RETURN(ANDassign);}
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 351 "CodeSmartCpp.l"
{NAMEDOP_RETURN(ERassign);}
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 352 "CodeSmartCpp.l"
{NAMEDOP_RETURN(ORassign);}
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 353 "CodeSmartCpp.l"
{NAMEDOP_RETURN(ELLIPSIS);}
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 357 "CodeSmartCpp.l"
ECHO;
	YY_BREAK
#line 1627 "CodeSmartCppLex.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 351 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 351 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 350);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 357 "CodeSmartCpp.l"


/* I won't bother to provide any error recovery. I won't  even  handle
unknown characters */

/*******************************************************************/
int isaTYPE(string)
char * string;
{
    /*  We  should  really  be  maintaining  a  symbol  table,  and be
    carefully keeping track of what the current scope is  (or  in  the
    case  of  "rescoped"  stuff,  what  scope  to  look in). Since the
    grammar is not annotated with  actions  to  track  transitions  to
    various  scopes,  and  there  is no symbol table, we will supply a
    hack to allow folks to test  the  grammar  out.   THIS  IS  NOT  A
    COMPLETE IMPLEMENTATION!!!! */

    return ('A' <= string[0] && 'Z' >= string[0]);
}
